### PR TITLE
Rebuild against latest version of libavif on Windows

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/conda-forge/libavif-feedstock/issues/32#issuecomment-2132358001 and https://github.com/conda-forge/libavif-feedstock/issues/33 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Would you like to help maintain this package?

**Comment by traversaro** [comment]
> Would you like to help maintain this package?

I never used it, and I opened the PR just to help on https://github.com/conda-forge/libavif-feedstock/issues/33, but why not, I added myself to the maintainers.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
